import type { Metadata } from "next";
import "./globals.css";
import SmoothScroll from "@/src/components/motion/SmothScroll";
import { Header } from "@/src/components/layout/Header";
import { Footer } from "@/src/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="font-intern h-full antialiased">
      <body className="relative flex min-h-full flex-col overflow-x-hidden">
        <Header />
        <main className="flex-1">
          <SmoothScroll>{children}</SmoothScroll>
        </main>
        <Footer />
      </body>
    </html>
  );
}
